max_file_uploads = 40;

;メモリ使用量の制限
memory_limit = 1024M
 
;POSTデータに許可される最大サイズ
post_max_size = 500M
 
;1つのファイルアップロードに許可される最大サイズ
upload_max_filesize = 500M

;タイムアウト
max_execution_time = 180;

; タイムゾーン設定
date.timezone = Asia/Tokyo
